{
 "title": "Bridge",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(coreum_contract_balance,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Coreum sender balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coreum_sender_balance{job=\"bridge\", exported_instance=~\"$instance\"}/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coreum pending unapproved transactions count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "coreum_pending_unapproved_transactions_count{job=\"bridge\", exported_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "start_time{job=\"bridge\", exported_instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coreum contract balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "coreum_contract_balance{job=\"bridge\", exported_instance=~\"$instance\"}/1000000",
     "legendFormat": "__auto"
    },
    {},
    {}
   ]
  },
  {
   "title": "Latest observer XRPL account ledger index",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "xrpl_latest_account_ledger_index{job=\"bridge\", exported_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "errors_total{job=\"bridge\", exported_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}