name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1' # At 01:00 on Monday
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "lint",
          "test",
          "integration tests",
          "contract lint and test"
        ]
        include:
          - ci_step: "lint"
            command: "make build-contract && make lint"
          - ci_step: "test"
            command: "make build-contract && make test"
          - ci_step: "integration tests"
            command: "make build-contract && make rebuild-dev-env && make restart-dev-env && make test-integration"
          - ci_step: "contract lint and test"
            command: "make test-contract"

    runs-on: self-hosted
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TX_CHAIN_PRIVATE_KEY }}
            ${{ secrets.TX_TOOLS_PRIVATE_KEY }}
            ${{ secrets.TX_CRUST_PRIVATE_KEY }}
      - name: Setup tx-chain acccess
        run: |
          export GOPRIVATE=github.com/tokenize-x GONOSUMDB=github.com:tokenize-x
          echo -e "${{ secrets.TX_CHAIN_PRIVATE_KEY }}" > ~/.ssh/tx-chain-deploy-key
          echo -e "${{ secrets.TX_TOOLS_PRIVATE_KEY }}" > ~/.ssh/tx-tools-deploy-key
          echo -e "${{ secrets.TX_CRUST_PRIVATE_KEY }}" > ~/.ssh/tx-crust-deploy-key
          chmod 600 ~/.ssh/tx-chain-deploy-key ~/.ssh/tx-tools-deploy-key ~/.ssh/tx-crust-deploy-key
          {
            echo -e "Host tx-chain-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-chain-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-tools-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-tools-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-crust-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-crust-deploy-key\n    IdentitiesOnly yes"
          } >> ~/.ssh/config
          {
            echo -e "[url \"git@tx-chain-private:tokenize-x/tx-chain\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-chain\""
            echo -e "[url \"git@tx-chain-private:tokenize-x/tx-chain\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-chain\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-crust\""
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-crust\""
          } > ~/.gitconfig
      - name: Checkout xrpl bridge
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: xrpl-bridge
          submodules: recursive
          fetch-depth: 0
      - name: Checkout coreum
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          repository: CoreumFoundation/coreum
          path: coreum
          ref: v5.0.1
          submodules: recursive
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Run ${{ matrix.ci_step }}
        working-directory: ./xrpl-bridge
        run: ${{ matrix.command }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
