name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout xrpl bridge
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: xrpl-bridge
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.TX_CHAIN_PRIVATE_KEY }}
            ${{ secrets.TX_TOOLS_PRIVATE_KEY }}
            ${{ secrets.TX_CRUST_PRIVATE_KEY }}
      - name: Setup tx-chain access
        run: |
          export GOPRIVATE=github.com/tokenize-x GONOSUMDB=github.com/tokenize-x
          echo -e "${{ secrets.TX_CHAIN_PRIVATE_KEY }}" > ~/.ssh/tx-chain-deploy-key
          echo -e "${{ secrets.TX_TOOLS_PRIVATE_KEY }}" > ~/.ssh/tx-tools-deploy-key
          echo -e "${{ secrets.TX_CRUST_PRIVATE_KEY }}" > ~/.ssh/tx-crust-deploy-key
          chmod 600 ~/.ssh/tx-chain-deploy-key ~/.ssh/tx-tools-deploy-key ~/.ssh/tx-crust-deploy-key
          {
            echo -e "Host tx-chain-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-chain-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-tools-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-tools-deploy-key\n    IdentitiesOnly yes"
            echo -e "Host tx-crust-private\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/tx-crust-deploy-key\n    IdentitiesOnly yes"
          } >> ~/.ssh/config
          {
            echo -e "[url \"git@tx-chain-private:tokenize-x/tx-chain\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-chain\""
            echo -e "[url \"git@tx-chain-private:tokenize-x/tx-chain\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-chain\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-tools-private:tokenize-x/tx-tools\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-tools\""
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"git@github.com:tokenize-x/tx-crust\""
            echo -e "[url \"git@tx-crust-private:tokenize-x/tx-crust\"]\n        insteadOf = \"https://github.com/tokenize-x/tx-crust\""
          } > ~/.gitconfig
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Build linux amd64
        working-directory: ./xrpl-bridge
        run: GOOS=linux GOARCH=amd64 make build
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+$ ]]; then
              echo ::set-output name=release_candidate::true
          fi
      - name: Link released binaries under right names
        run: |
          ln xrpl-bridge/artifacts/relayer relayer-linux-amd64
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            relayer-linux-amd64
